#ifndef GITHUB_REPO_PIN_DEFINITIONS_H
#define GITHUB_REPO_PIN_DEFINITIONS_H

#define PIN_BUTTON_PREV 2
#define PIN_BUTTON_NEXT 3
#define PIN_BUTTON_RETURN 4
#define PIN_BUTTON_ENTER 5

#define PIN_RELAY_SIGNAL 6

#define PIN_ENCODER_CLK 7
#define PIN_ENCODER_DT 8

#define PIN_RGB_LED_RED 9
#define PIN_RGB_LED_GRE 10
#define PIN_RGB_LED_BLU 11

#define PIN_SERVO_SIGNAL 12

#define PIN_SENSOR_AUX_LED 13

#define PIN_STEPPER_IN1 17
#define PIN_STEPPER_IN2 16
#define PIN_STEPPER_IN3 15
#define PIN_STEPPER_IN4 14

#define DISPLAY_ADDRESS 0x27
#define DISPLAY_ROWS 2
#define DISPLAY_COLUMNS 16

#define DEBOUNCE_DELAY 50
#define REST_DELAY 50

#endif //GITHUB_REPO_PIN_DEFINITIONS_H
